# coding: utf-8

"""
    gaqqie user API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: tknsryk@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Jobbeforesubmission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'provider_name': 'str',
        'device_name': 'str',
        'instructions': 'str'
    }

    attribute_map = {
        'name': 'name',
        'provider_name': 'provider_name',
        'device_name': 'device_name',
        'instructions': 'instructions'
    }

    def __init__(self, name=None, provider_name=None, device_name=None, instructions=None):  # noqa: E501
        """Jobbeforesubmission - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._provider_name = None
        self._device_name = None
        self._instructions = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if provider_name is not None:
            self.provider_name = provider_name
        self.device_name = device_name
        self.instructions = instructions

    @property
    def name(self):
        """Gets the name of this Jobbeforesubmission.  # noqa: E501


        :return: The name of this Jobbeforesubmission.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Jobbeforesubmission.


        :param name: The name of this Jobbeforesubmission.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def provider_name(self):
        """Gets the provider_name of this Jobbeforesubmission.  # noqa: E501


        :return: The provider_name of this Jobbeforesubmission.  # noqa: E501
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name):
        """Sets the provider_name of this Jobbeforesubmission.


        :param provider_name: The provider_name of this Jobbeforesubmission.  # noqa: E501
        :type: str
        """

        self._provider_name = provider_name

    @property
    def device_name(self):
        """Gets the device_name of this Jobbeforesubmission.  # noqa: E501


        :return: The device_name of this Jobbeforesubmission.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this Jobbeforesubmission.


        :param device_name: The device_name of this Jobbeforesubmission.  # noqa: E501
        :type: str
        """
        if device_name is None:
            raise ValueError("Invalid value for `device_name`, must not be `None`")  # noqa: E501

        self._device_name = device_name

    @property
    def instructions(self):
        """Gets the instructions of this Jobbeforesubmission.  # noqa: E501


        :return: The instructions of this Jobbeforesubmission.  # noqa: E501
        :rtype: str
        """
        return self._instructions

    @instructions.setter
    def instructions(self, instructions):
        """Sets the instructions of this Jobbeforesubmission.


        :param instructions: The instructions of this Jobbeforesubmission.  # noqa: E501
        :type: str
        """
        if instructions is None:
            raise ValueError("Invalid value for `instructions`, must not be `None`")  # noqa: E501

        self._instructions = instructions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Jobbeforesubmission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Jobbeforesubmission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
